### ISSUE TITLE
fs.write is void, does not return a promise

### ISSUE THREAD

**Issue by emarteca** [adi-g15/Useful_APIs#9]
[Here](https://github.com/adi-g15/Useful_APIs/blob/master/apis/doist15/routes/index.js#L27) there is a `catch` call on the return of the `write` function from the `fs` library. However, this function is void does not return a promise.

[Error handling with `fs.write`](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_write_fd_string_position_encoding_callback) is done with a callback. This code should probably be written as:
```
write("./offlineData/todos.json", JSON.stringify(json), (err, written, str) => {
    console.error("Problem Saving offline -> ", err);
});
```

**Comment by adi-g15** [comment]
> [Here](https://github.com/adi-g15/Useful_APIs/blob/master/apis/doist15/routes/index.js#L27) there is a `catch` call on the return of the `write` function from the `fs` library. However, this function is void does not return a promise.
> 
> [Error handling with `fs.write`](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_write_fd_string_position_encoding_callback) is done with a callback. This code should probably be written as:
> 
> ```
> write("./offlineData/todos.json", JSON.stringify(json), (err, written, str) => {
>     console.error("Problem Saving offline -> ", err);
> });
> ```

Thanks for pointing that out, but right now as i see it, [the code itself is wrong](https://devdocs.io/node/fs#fs.write()) :' ( , maybe the API changed or something, the docs tell write takes a file descriptor instead of the filename.
> Also there's two require("fs"), i guess I didn't used to do that 🤔

Btw, I will correct it, thanks for creating this issue though, seeing the code again was great, i hadn't coded in js for sometime 😅

**Comment by emarteca** [comment]
Thanks for looking at this so quickly! Good point about the API difference. I mainly see people using [`fs.writeFile`](https://nodejs.org/api/fs.html#fswritefilefile-data-options-callback) or the synchronous version [`fs.writeFileSync`](https://nodejs.org/api/fs.html#fswritefilesyncfile-data-options) -- these functions both take the file name as an argument.

**Comment by adi-g15** [comment]
Thank you for the suggestion :+1:, and also for referencing them with links to the docs.

https://github.com/adi-g15/Useful_APIs/blob/131bbc0bcda44b03cf93ac35138f9cffc71ff771/apis/doist15/routes/index.js#L28-L30

Used the one returning a promise, Corrected in https://github.com/adi-g15/Useful_APIs/commit/131bbc0bcda44b03cf93ac35138f9cffc71ff771

**Comment by emarteca** [comment]
Awesome, thank you!
